binary:
  frisomum:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  gold:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  prestige:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  stage_f0:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  stage_f1:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  stage_f2:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  stage_f3:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
  stage_f4:
    true_values:
    - '1'
    - y
    - 'yes'
    - 'true'
continuous:
  baby_age_last_order:
    fill_value: 7.131169957310566
    mean: 7.131169957310566
    std: 17.945106236702237
  baby_residual_lifecycle:
    fill_value: 1289.562696448873
    mean: 1289.5626964488733
    std: 187.21544866529032
  last_repurchase_interval:
    fill_value: 106.69086576648134
    mean: 106.69086576648132
    std: 103.05728304412813
nominal:
  reg_channel:
    categories:
    - CRM系统
    - KA合作伙伴
    - 一号店
    - 京东商城
    - 其他
    - 品牌微信
    - 天猫旗舰店
    - 官方网站
    - 电商平台
    - 线下
    - 美囤
    - 苏宁
    - 蜜芽
ordinal: {}
