baby_age_last_order: continuous
baby_residual_lifecycle: continuous
customer_lifecycle_finished_flag: nominal
dac_id: id
frisomum: binary
gold: binary
last_repurchase_interval: continuous
prestige: binary
reg_channel: nominal
stage_f0: binary
stage_f1: binary
stage_f2: binary
stage_f3: binary
stage_f4: binary
